# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ktau_cpp <- function(x, y, weights) {
    .Call(`_wdm_ktau_cpp`, x, y, weights)
}

#' @export
hoeffd_cpp <- function(x, y, weights) {
    .Call(`_wdm_hoeffd_cpp`, x, y, weights)
}

#' @export
prho_cpp <- function(x, y, weights) {
    .Call(`_wdm_prho_cpp`, x, y, weights)
}

#' @export
srho_cpp <- function(x, y, weights) {
    .Call(`_wdm_srho_cpp`, x, y, weights)
}

#' @export
rank_scores_cpp <- function(x, weights) {
    .Call(`_wdm_rank_scores_cpp`, x, weights)
}

#' @export
bivariate_rank_cpp <- function(x, y, weights) {
    .Call(`_wdm_bivariate_rank_cpp`, x, y, weights)
}

#' @export
indep_test_asymptotic_cpp <- function(x, y, method, weights) {
    .Call(`_wdm_indep_test_asymptotic_cpp`, x, y, method, weights)
}

#' @export
indep_test_bootstrap_cpp <- function(x, y, method, weights, n_boot, seed) {
    .Call(`_wdm_indep_test_bootstrap_cpp`, x, y, method, weights, n_boot, seed)
}

